# Welcome to Sinai Jekyll Theme!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
# bundle exec jekyll serve --livereload

theme_version: 1.0.2

# Site settings
title:              Pin Drop Silence
logo:               # Logo image URL
description:        Thoughts, Stories and Ideas
# baseurl:            '/pindropsilence' # The subpath of your site, e.g. /blog
url:                'https://amlervishal.github.io' # The base hostname & protocol for your site
twitter:            https://mobile.twitter.com/dramrita5
facebook:           https://www.facebook.com/dramrita5
instagram:          https://instagram.com/amrita.aneja?utm_medium=copy_link
linkedin:           http://linkedin.com/in/dr-amrita-vohra-a4625b91

markdown:  kramdown
permalink: pretty
paginate:  12
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext